name: build

on:
 workflow_call:
 workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build an image from Dockerfile
        run: docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

      - name: Upload the built image tag for scanning
        id: image_tag
        run: echo "IMAGE_TAG=docker.io/my-organization/my-app:${{ github.sha }}" >> $GITHUB_ENV

  container-image-scan:
    name: Container Image Scan
    runs-on: ubuntu-latest
    needs: build  # This ensures that this job runs after the build job
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Pull the built image
        run: docker pull ${{ env.IMAGE_TAG }}
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0  # Update to the latest version
        with:
          image-ref: ${{ env.IMAGE_TAG }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
