name: 51 Scan Docker Image

on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        description: 'The tag of the docker image to scan'
        required: true

  workflow_call:
    inputs:
      image-tag:
        type: string
        description: 'The tag of the docker image to scan'
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: anshumaan-10/devsecops-github-actions
  IMAGE_TAG: ${{ inputs.image-tag }}

jobs:
  container-image-scan:
    name: Container Image Scan
    permissions:
      contents: read
      checks: write
      pull-requests: write
      issues: read
      actions: read
      security-events: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      # Checkout code (if required)
      - name: Checkout Code
        uses: actions/checkout@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Pull Docker Image
      - name: Pull Docker Image
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # List Docker Images
      - name: List Docker Images
        run: docker images

      # Login to Docker Hub (if needed for Docker Hub images)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Run Docker Scout Scan
      - name: Docker Scout Scan
        uses: docker/scout-action@v1.0.9
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          command: quickview,cves
          only-severities: critical,high
          sarif-file: scout-report.sarif
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Upload Artifact
      - name: Upload Scout Report Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: docker-scout-findings
          path: scout-report.sarif
