name: "Build and Push Docker Image to GHCR or GAR"

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      image-tag:
        description: 'The image tag of the new Docker image'
        value: ${{ jobs.docker.outputs.image-tag }}

env:
  REGISTRY_GHCR: 'ghcr.io'
  REGISTRY_GAR: 'asia-south1-docker.pkg.dev'  # Adjust this to your GAR location
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout the repository
      - name: Check out the code
        uses: actions/checkout@v3
      
      # Download application binary artifact
      - name: Download application binary
        uses: actions/download-artifact@v3.0.0
        with:
          name: Application-Binary
          path: target

      # Set the target container registry based on the branch
      - name: Set REGISTRY environment variable
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "REGISTRY=${{ env.REGISTRY_GAR }}" >> $GITHUB_ENV
          else
            echo "REGISTRY=${{ env.REGISTRY_GHCR }}" >> $GITHUB_ENV
          fi

      # Authenticate with Google Cloud if using GAR
      - name: Authenticate with Google Cloud
        if: env.REGISTRY == env.REGISTRY_GAR
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Set up the Google Cloud SDK
      - name: Set up Google Cloud SDK
        if: env.REGISTRY == env.REGISTRY_GAR
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'avian-voice-433417-d5'  # Replace with your GCP project ID

      # Authenticate to GHCR if using GHCR
      - name: Log in to GitHub Container Registry (GHCR)
        if: env.REGISTRY == env.REGISTRY_GHCR
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata for Docker image tags and labels
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.1.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=pr
            type=ref,event=tag
            type=ref,event=branch
            type=schedule,pattern=main

      # Build and push the Docker image to the selected registry
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
