name: "Build and Push Docker Image to GHCR or GAR"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (optional)'
        required: false
        default: 'latest'  # Default value for the tag if not provided
  workflow_call:
    outputs:
      image-tag:
        description: 'The image tag of the new Docker image'
        value: ${{ jobs.docker.outputs.image-tag }}

env:
  REGISTRY_GHCR: 'ghcr.io'
  REGISTRY_GAR: 'asia-south1-docker.pkg.dev'  # Adjust to your GAR location

jobs:
  docker:
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Step 1: Checkout the repository code
      - name: Check out the code
        uses: actions/checkout@v3
      
      # Step 2: Download the application binary artifact (if required)
      - name: Download application binary
        uses: actions/download-artifact@v3.0.0
        with:
          name: Application-Binary
          path: target

      # Step 3: Set REGISTRY environment variable based on branch
      - name: Set REGISTRY environment variable
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "REGISTRY=${{ env.REGISTRY_GAR }}" >> $GITHUB_ENV
          else
            echo "REGISTRY=${{ env.REGISTRY_GHCR }}" >> $GITHUB_ENV
          fi

      # Step 4: Authenticate with Google Cloud for GAR
      - name: Authenticate with Google Cloud
        if: env.REGISTRY == env.REGISTRY_GAR
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Step 5: Set up Google Cloud SDK (required for GAR push)
      - name: Set up Google Cloud SDK
        if: env.REGISTRY == env.REGISTRY_GAR
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'avian-voice-433417-d5'  # Replace with your GCP project ID

      # Step 6: Authenticate Docker with Google Cloud for GAR
      - name: Configure Docker to use Google Cloud
        if: env.REGISTRY == env.REGISTRY_GAR
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      # Step 7: Authenticate to GHCR if targeting GHCR
      - name: Log in to GitHub Container Registry (GHCR)
        if: env.REGISTRY == env.REGISTRY_GHCR
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: Set the IMAGE_NAME variable based on the tag
      - name: Set IMAGE_NAME
        id: set-image-name
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "IMAGE_NAME=${{ env.REGISTRY }}/avian-voice-433417-d5/asia-south1-docker-images-multiregion-prod/${{ github.event.inputs.tag || 'latest' }}" >> $GITHUB_ENV
          else
            echo "IMAGE_NAME=${{ env.REGISTRY }}/${{ github.repository }}:${{ github.event.inputs.tag || 'latest' }}" >> $GITHUB_ENV
          fi

      # Step 9: Extract Docker metadata for tags and labels
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.1.0
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ github.event.inputs.tag || 'latest' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=pr
            type=ref,event=tag
            type=ref,event=branch
            type=schedule,pattern=main

      # Step 10: Build the Docker image
      - name: Build Docker Image
        id: build-image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .

      # Step 11: Push Docker image to Google Artifact Registry (GAR)
      - name: Push Docker Image to GAR
        if: env.REGISTRY == env.REGISTRY_GAR
        run: |
          # Ensure the IMAGE_NAME is correctly formatted for GAR
          GAR_IMAGE_NAME="${{ env.REGISTRY }}/${{ github.repository }}:${{ github.event.inputs.tag || 'latest' }}"
          echo "Pushing image to GAR: $GAR_IMAGE_NAME"
          docker push $GAR_IMAGE_NAME

      # Step 12: Push Docker image to GitHub Container Registry (GHCR)
      - name: Push Docker Image to GHCR
        if: env.REGISTRY == env.REGISTRY_GHCR
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev
          docker push ${{ env.IMAGE_NAME }}

      # Step 13: Output the image tag and path
      - name: Output image details
        run: |
          echo "Image tag is: ${{ github.event.inputs.tag || 'latest' }}"
          echo "Image path is: ${{ env.IMAGE_NAME }}"
