# File: .github/workflows/mutation-test.yaml

on:
  # Run the mutation tests when changes are pushed to the main branch
  push:
    branches:
      - 'main'

jobs:
  mutation-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run Stryker Mutation Tests
        uses: stryker-mutator/github-action@v0.0.1
        with:
          testProject: "BusinessLogic.Test/" # required
          breakAt: "75" # Optional

      - name: Upload Mutation Test Report
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: ${{ github.workspace }}/BusinessLogic.Test/StrykerOutput/**/*.html
