# File: .github/workflows/mutation-test.yaml

on:
  # Run the mutation tests when changes are pushed to the main branch
  push:
    branches:
      - 'main'

jobs:
  mutation-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Mutation Annotation Report
        uses: johanholmerin/mutation-report-action@0.2.0
        if: ${{ always() }} # Upload even if tests don't pass testing threshold
        with:
          repo-token: '${{ secrets.PAT_TOKEN }}'
          report-json: './reports/mutation/mutation.json' # Optional, default
